name: gpu-venv
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - fftw=3.3.9
  - fonttools=4.25.0
  - freetype=2.10.4
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icc_rt=2022.1.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.8.0
  - jedi=0.18.1
  - joblib=1.1.1
  - jpeg=9e
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - kiwisolver=1.4.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libffi=3.4.2
  - libiconv=1.17
  - libogg=1.3.4
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.0.9
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvmlite=0.39.1
  - lz4-c=1.9.3
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nest-asyncio=1.5.6
  - numba=0.56.4
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=23.0
  - parso=0.8.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - platformdirs=2.5.2
  - ply=3.11
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.10.9
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pywin32=305
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - scikit-learn=1.2.0
  - scipy=1.9.3
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.40.1
  - stack_data=0.2.0
  - tbb=2021.7.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.7.1
  - tzdata=2022g
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.38.4
  - wincertstore=0.2
  - xz=5.2.10
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - cachetools==5.3.0
      - charset-normalizer==3.0.1
      - flatbuffers==23.3.3
      - gast==0.4.0
      - google-auth==2.16.2
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.51.3
      - h5py==3.8.0
      - idna==3.4
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - libclang==15.0.6.1
      - markdown==3.4.1
      - markupsafe==2.1.2
      - numpy==1.24.2
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==3.19.6
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - python-version==0.0.2
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.0
      - tensorflow-estimator==2.10.0
      - tensorflow-intel==2.11.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.2.0
      - typing-extensions==4.5.0
      - urllib3==1.26.14
      - werkzeug==2.2.3
      - wrapt==1.15.0
